#88 - Feed de denúncias
Eccoar/2020.2-eccoar_front-end pull request #10
Opened 2021-03-20 03:09 UTC by luiz-herique

## Conteúdo
Criação e estilização da Home e integração com Back-end

Neste pull request se realizou:
* Criação e estilização da pagina de Home
* Testes do Card e Home
* Correção de bug no Card

2021-03-20 17:50 UTC, Phe0 commented
@luiz-herique @Victor-Buendia  como não foi feia configuração de rota nesse pr, quero que esperem o [esse PR](https://github.com/Eccoar/2020.2-eccoar_front-end/pull/11) ser aceito primeiro e então vcs configurem uma rota para essa página, ela deve ser a página de caminho "/"

2021-03-20 17:52 UTC, Phe0 commented
coloquei o PR como WIP, coloquem como Solve quando terminarem de fazer o ajuste

2021-03-20 18:39 UTC, devsalula commented
Marquem os EPSs como reviewers por favor!

2021-03-20 23:07 UTC, MatheusBlanco requested changes

2021-03-20 23:07 UTC, MatheusBlanco commented on src/pages/Home.tsx
> +	return (
acho interessante tirar essa função de dentro do useEffect. O funcionamento vai ser o mesmo, mas se quisermos adicionar mais funções nele depois, seria mais limpo só declararmos as mesmas lá dentro. 

Poderia ficar assim:
```
	const handleComplaint = async () => {
		const result = await listComplaints();
		setData(result);
	};

       useEffect(() => {
		handleComplaint();
	}, []);
```

Lembrem de tirar os console.logs também

2021-03-21 12:43 UTC, MatheusBlanco approved these changes

2021-03-22 20:03 UTC, devsalula requested changes
Galera uns ajustes

2021-03-22 20:03 UTC, devsalula commented on src/styles/Home.scss
> +}
Outra coisa, quando eu rodei o projeto, eu dei um scroll na tela nas denúncias e elas estão estourando o tamanho da tela.
Exemplo na imagem:
![Captura de tela de 2021-03-22 16-51-53](https://user-images.githubusercontent.com/35435199/112050686-e95f6900-8b2f-11eb-9a61-7f75de12e148.png)

Minha sugestão é nessa classe de SCSS, vocês mudarem o height para 100% e adicionarem um campo chamado `overflow: scroll`. Acho que isso aqui já resolve.
Com a classe ficando assim:
```
.scrollHome{
     height: 100%;
    overflow: scroll;
}
```

Reparem que eu tirei o Margin top, ele não é necessário, podem remover.

2021-03-22 20:03 UTC, devsalula commented on src/styles/complainCard.scss
> +    // flex-grow: 1;
remover

2021-03-23 03:13 UTC, Victor-Buendia commented
Vou ajudar nessa aqui hoje mais tarde!

2021-03-23 14:33 UTC, devsalula approved these changes

2021-03-23 16:38 UTC, merged