WIP #93 Formulário de denúncias
Eccoar/2020.2-eccoar_front-end pull request #11
Opened 2021-03-20 17:46 UTC by DLBrianPina

Neste pull request se realizou:
* US 10
* Criação do sistema de rotas

2021-03-20 20:02 UTC, Arthur-Matos commented
Os testes estão fazendo atividades semelhantes para telas diferentes, por isso, existe uma repetição de código em algumas partes. Não sei se é possível modularizar essas partes dentro dos arquivos de teste

2021-03-20 20:42 UTC, MatheusBlanco approved these changes

2021-03-20 22:35 UTC, devsalula requested changes
Dá uma olhada nos comentários que deixei.
Alguns testes quebraram quando rodei. Eram para terem quebrados mesmo?

2021-03-20 22:35 UTC, devsalula commented on src/services/complaint.ts
> +		return await api.post('/complaint', {
Mudar a rota aqui, para a rota que chama agora no gateway

2021-03-20 22:35 UTC, devsalula commented on src/services/complaint.ts
> +			status: true,
Não passa mais status como parâmetro

2021-03-21 20:30 UTC, devsalula requested changes
Primeiro, parabéns pelo trabalho no Front!
Mas 3 coisas que gostaria de pontuar e 2 que quero que vocês arrumem.

1. O formulário de denúncias está permitindo que eu envie uma denúncia sem preencher os campos, como no vídeo abaixo. Por favor, coloquem uns validores nos campos do formulário, em conformidade com os campos que são obrigatórios lá na tabela no banco de dados. 


https://user-images.githubusercontent.com/35435199/111919991-46ddb200-8a6b-11eb-9e24-4174d25fbef2.mp4





2. No vídeo que coloquei acima vocês podem perceber que o input de título possui placeholder e os outros campos não. Para ficar coerente com o protótipo, removam o placeholder do campo de título, por favor.

3. Aqui, não precisem arrumar nesse PR só estou comentando por fim de documentação. Mas as cores vermelhas no darkmode não estão em conformidade com o que está no protótipo também.

2021-03-22 18:32 UTC, devsalula approved these changes
Boa @DLBrianPina e @Arthur-Matos

2021-03-22 18:32 UTC, merged