Fixing colors, responsiveness and background
Eccoar/2020.2-eccoar_front-end pull request #12
Opened 2021-03-21 21:18 UTC by MatheusBlanco

Neste pull request se realizou:
* Correção de bug nas cores do darkmode, responsividade do drawer e background

## Checklist 
- [ ] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers). 
- [ ] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [ ] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ ] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [ ] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue). 
- [ ] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [ ] Escrever o título do pull request no formato correto, conforme as referências abaixo: 

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:
* Solve #X IssueName (Caso Padrão)
* WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-03-22 18:33 UTC, devsalula commented
@MatheusBlanco tem conflito.
Outra coisa, quando rodei, tem alguns testes que quebraram com ele.

2021-03-22 18:34 UTC, devsalula requested changes
@MatheusBlanco tem conflito.
Outra coisa, quando rodei, tem alguns testes que quebraram com ele.

2021-03-22 23:25 UTC, devsalula commented
@MatheusBlanco olha a pilha de commits, que ela está duplicada. Consegue corrigir?

2021-03-22 23:27 UTC, MatheusBlanco commented
> @MatheusBlanco olha a pilha de commits, que ela está duplicada. Consegue corrigir?

Vou tentar, mas nunca mexi com nada assim n kkk

2021-03-23 17:39 UTC, devsalula commented
@MatheusBlanco depois que merjaram o ultimo PR, rolou mais conflito aqui.

2021-03-23 19:21 UTC, MatheusBlanco commented
> @MatheusBlanco depois que merjaram o ultimo PR, rolou mais conflito aqui.

Pronto, pode ver novamente?

2021-03-23 20:15 UTC, devsalula approved these changes
Dei approve. Só ajusta as paradas que eu pedi, pfvr.

2021-03-23 20:15 UTC, devsalula commented on src/components/Drawer.tsx
> +
Linha em branco, apagar

2021-03-23 20:15 UTC, devsalula commented on src/styles/base/_app.scss
> +}
Ajustar a chaves do CSS

2021-03-23 20:53 UTC, Victor-Buendia approved these changes

2021-03-23 21:04 UTC, merged