Solve #90 US23 - Confirmação de resolução da denúncia
Eccoar/2020.2-eccoar_front-end pull request #13
Opened 2021-03-26 22:38 UTC by Arthur-Matos

Neste pull request se realizou:

* US 23
* Testes
* Confirmed addVote 
* Botão de voto confirmado

2021-03-27 18:07 UTC, MatheusBlanco commented
Ainda terão mudanças aqui, certo? Vou deixar comentado só pra receber notificações

2021-03-29 17:03 UTC, devsalula commented
@MatheusBlanco o Arthur subiu a fix, já pode revisar.

2021-03-29 17:47 UTC, MatheusBlanco requested changes
Massa. Pedi umas alterações pro Arthur, na linha do que estava sendo feito no PR do Sabanai, de n deixar o usuário votar duas vezes no mesmo e mudar a cor do botão

2021-03-29 23:40 UTC, Arthur-Matos commented
O PR foi transferido para #14

2021-03-29 23:40 UTC, closed without merging