Solve #125 US17 Criação da página de detalhamento de denúncia
Eccoar/2020.2-eccoar_front-end pull request #16
Opened 2021-04-03 12:30 UTC by Victor-Buendia

## Conteúdo
Criação da página de detalhamento da denúncia, sua estilização e funcionamento pleno com o back através da gateway.

Neste pull request se realizou:
* Criação da nova página
* Criação das rotas para a nova página
* Criação dos estados para puxar a informação do voto
* Aprimoramento do componente do botão para mudar o texto de acordo com o tipo da denúncia e se foi votada ou não
* Aprimoramento do componente do botão para mudar seu tamanho de fonte e altura quando estiver na página de detalhamento
* Estilização com um novo SCSS para a nova página
* Testes no front

## Checklist 
- [ ] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers). 
- [ ] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [ ] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ ] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [ ] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue). 
- [ ] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [ ] Escrever o título do pull request no formato correto, conforme as referências abaixo: 

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:
* Solve #X IssueName (Caso Padrão)
* WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-04-03 12:31 UTC, Victor-Buendia commented
Falta arrumar o tamanho fixo da imagem.

2021-04-03 12:42 UTC, Victor-Buendia commented
Arrumado!

2021-04-03 15:18 UTC, MatheusBlanco requested changes
Parabéns gente. Só vi um erro aqui agora, a responsividade foi meio afetada 

![image](https://user-images.githubusercontent.com/37380789/113482792-a3cb6600-9476-11eb-9959-306f9f0f6b71.png)

2021-04-03 15:25 UTC, devsalula requested changes
Dá uma olhada no que o @MatheusBlanco comentou e tem teste quebrando também gente.

2021-04-03 15:36 UTC, devsalula requested changes

2021-04-03 15:36 UTC, devsalula commented on src/services/complaint.ts
> +	const response = await api.get('/complaint/withVote', {
Mesmo comentário que fiz no back. Trocar a taxonomia para `complaint/votes` na nomeação da rota

2021-04-06 13:59 UTC, MatheusBlanco approved these changes

2021-04-07 17:48 UTC, devsalula requested changes
Galera, parabéns pelo trabalho!!
Antes de aprovar, quero pedir para vocês darem uma olhada no caso em que se cria uma denúncia sem foto e abre os detalhes dela.

![denuncia](https://user-images.githubusercontent.com/35435199/113911030-e0b59680-97af-11eb-8c95-13f677d22fcf.gif)

No GIF, eu encontrei 3 probleminhas para vocês corrigirem:
1º - A Tela está dando scroll sem ter conteúdo para baixo.
2º - Aonde deveria estar a imagem tem um frase na cor preta. No caso em que não tem imagem, deixe essa área preenchida apenas com a descrição da denúncia.
3º - Ao lado do título de denúncia, vocês pode reparar está sobrando uma corzinha azul ali no cantinho direito da tela. Não sei se isso é porque o título está muito grande ou se é por conta do scroll que tá zoado. 

No geral é isso. Qualquer dúvida é só chamar.

2021-04-07 17:48 UTC, devsalula commented on src/tests/components/Button.test.tsx
> +	test('test check icon', () => {
Coloca uma quebra de linha entre a 28 e a 29

2021-04-08 00:45 UTC, Victor-Buendia commented
@devsalula , acabei de ver aqui suas revisões! Amanhã de manhã vou olhar e já tentar resolver essa questão. Peço perdão pelas inconveniências :(

2021-04-08 17:14 UTC, Victor-Buendia commented
@devsalula Bugs corrigidos.

2021-04-09 03:53 UTC, devsalula approved these changes
Show de Top!!! Ficou Irado! Grande trabalho @Victor-Buendia e @luiz-herique

2021-04-09 03:53 UTC, merged