97 configuracao pipeline
Eccoar/2020.2-eccoar_front-end pull request #17
Opened 2021-04-08 23:56 UTC by guilhesme23

## Conteúdo

Adiciona gitlabci, helm chart e sonar properties

Stages implementados até o momento:

- Linting
- Tests
- sonar scan
- coleta de métricas
- build da imagem
- build do chart
- deploy em hm

Adiciona também variável de ambiente para host do gateway
Implementa protocolo https

2021-04-09 04:19 UTC, devsalula requested changes
Pipeline tá top!
@guilhesme23 consegue corrigir só o bugzinho do sonar pfvr?
Ele tá xaropando no arquivo complaintCard.tsx, no trecho de código que tem isso aqui:
```
	<button
		type='button'
		onClick={() => {
			!isConfirmed
				? (onClick(), setConfirmed(true))
				: alert('Denuncia já votada');
		}}
		data-testid='button-id'
		className={complaintStatus}
	>
		{renderIcon()}
	</button>
```
Eu acho que o problema é esse ternário no onClick que está recebendo duas funções. Minha sugestão para você mudar isso aí é criar uma função chamada `checkIsVoted` e chamar ela dentro desse onClick. Na implementação da função você faria algo desse jeito:
```
const checkIsVoted = () => {
     if (!isConfirmed) {
         onClick();
         setConfirmed(true);
     } else {
          alert('Denuncia já votada');
     }
}
```

Acho que isso já resolve. O @Phe0 pode ter uma solução melhor.

2021-04-09 17:41 UTC, Phe0 commented
> Pipeline tá top!
> @guilhesme23 consegue corrigir só o bugzinho do sonar pfvr?
> Ele tá xaropando no arquivo complaintCard.tsx, no trecho de código que tem isso aqui:
> 
> ```
> 	<button
> 		type='button'
> 		onClick={() => {
> 			!isConfirmed
> 				? (onClick(), setConfirmed(true))
> 				: alert('Denuncia já votada');
> 		}}
> 		data-testid='button-id'
> 		className={complaintStatus}
> 	>
> 		{renderIcon()}
> 	</button>
> ```
> 
> Eu acho que o problema é esse ternário no onClick que está recebendo duas funções. Minha sugestão para você mudar isso aí é criar uma função chamada `checkIsVoted` e chamar ela dentro desse onClick. Na implementação da função você faria algo desse jeito:
> 
> ```
> const checkIsVoted = () => {
>      if (!isConfirmed) {
>          onClick();
>          setConfirmed(true);
>      } else {
>           alert('Denuncia já votada');
>      }
> }
> ```
> 
> Acho que isso já resolve. O @Phe0 pode ter uma solução melhor.

Acho essa uma boa solução, só arrumar q eu já aceito aqui tmb

2021-04-09 19:33 UTC, guilhesme23 commented
Correção feita

2021-04-10 14:49 UTC, devsalula commented
@guilhesme23 uma parada, o PR está em WIP. Posso revisar? Ou ainda vai entrar mais coisa?

Outra coisa, você pode colocar as badges da pipeline no readme, pfvr?

2021-04-10 21:23 UTC, MatheusBlanco approved these changes

2021-04-10 21:27 UTC, guilhesme23 commented
> @guilhesme23 uma parada, o PR está em WIP. Posso revisar? Ou ainda vai entrar mais coisa?

Eu tinha esquecido de retirar o wip, não vai entrar mais nada não

2021-04-13 16:55 UTC, devsalula requested changes
Só uma última coisa e uma dúvida e dou o approve

2021-04-13 16:55 UTC, devsalula commented on .gitignore
> +.env
.env está duplicado. Deleta o da linha 27.

2021-04-13 16:55 UTC, devsalula commented on Dockerfile
> +FROM node:14-alpine
Uma dúvida. Na linha 1 tem uma imagem do node já sendo baixada. Essa aqui é necessária? Só uma dúvida mesmo.

2021-04-16 20:46 UTC, guilhesme23 commented on Dockerfile
> +FROM node:14-alpine
Yep, são builds diferentes dentro do mesmo Dockerfile

2021-04-16 20:48 UTC, guilhesme23 commented on .gitignore
> +.env
pronto

2021-04-17 12:35 UTC, devsalula approved these changes

2021-04-17 12:36 UTC, merged