WIP 14 Refatorar código do front-end
Eccoar/2020.2-eccoar_front-end pull request #19
Opened 2021-04-10 13:12 UTC by Sabanai104

Neste pull request se realizou:
* US 145
* Adição de uma seta de voltar na navbar em todas as telas, exceto na de denuncias;
* Criação de testes na navbar.

2021-04-10 16:01 UTC, MatheusBlanco requested changes
@Sabanai104 , ficou perfeito. Mas uma coisa que quebrou foi o scroll da página página principal. Ele parou de funcionar. Estou adicionando um gif das tentativas de scrollar

![Screen Capture_peek_20210410125906](https://user-images.githubusercontent.com/37380789/114276384-c3293c80-99fc-11eb-9693-54155535fab4.gif)

2021-04-10 17:14 UTC, MatheusBlanco commented
> @Sabanai104 , ficou perfeito. Mas uma coisa que quebrou foi o scroll da página página principal. Ele parou de funcionar. Estou adicionando um gif das tentativas de scrollar
> 
> ![Screen Capture_peek_20210410125906](https://user-images.githubusercontent.com/37380789/114276384-c3293c80-99fc-11eb-9693-54155535fab4.gif)

Checa o background também, agora que eu vi que sumiu

2021-04-14 22:17 UTC, MatheusBlanco requested changes

2021-04-14 22:17 UTC, MatheusBlanco commented on src/tests/components/NavBar.test.tsx
> +});
Esse teste tá comentado. Está funcionando?

2021-04-14 22:17 UTC, MatheusBlanco commented
Ficou ótimo, só ver a questão do teste e por favor tira de WIP se for pra gente revisar

2021-04-17 14:48 UTC, luiz-herique commented
parabéns pelo trabalho, ficou incrível, apenas corrigir o teste está comendado.

2021-04-17 14:52 UTC, luiz-herique requested changes

2021-04-17 14:52 UTC, luiz-herique commented on src/tests/components/NavBar.test.tsx
> +	// });
parabéns pelo trabalho, ficou incrível, apenas corrigir o teste está comendado.

2021-04-22 19:07 UTC, Sabanai104 commented
Criados todos os testes!

2021-04-22 19:23 UTC, MatheusBlanco requested changes
Boa! Última coisa agora, para eu poder aprovar. Agora que o sistema está com a rota Home, tem dois fix para fazer. Quando eu ligo ele, ele não está indo para a home direto, então não consigo ver as denúncias de cara. E quando eu clico em "VER DENÚNCIAS" no drawer, ele me leva para a rota "/", que não tem mais denúncias.

2021-04-25 14:29 UTC, luiz-herique approved these changes

2021-04-25 14:33 UTC, merged