WIP - #126 Upload de fotos #12
Eccoar/2020.2-eccoar_front-end pull request #21
Opened 2021-04-11 04:07 UTC by Sabanai104

Neste pull request se realizou:
* US 11
* Requisição da imagem pelo front.

2021-04-11 12:53 UTC, MatheusBlanco commented
Esse PR ainda está em WIP? Ou já posso corrigir? @Sabanai104

2021-04-12 13:58 UTC, MatheusBlanco requested changes
Massa gente. Ficou ótimo. Mas queria pedir umas alterações, além dos testes que estão faltando. O sistema está aceitando upload de documento PDF, sendo que a issue pede apenas imagem. Queria pedir para que bloqueassem a entrada de PDF, mesmo que apenas no front

2021-04-21 05:12 UTC, Sabanai104 commented
Limitei o tipo de arquivo apenas para jpeg e png mas os testes tão me destruindo, help please

2021-04-26 12:47 UTC, DLBrianPina approved these changes
Bom trabalho! 🏆🏆🏆
Favor mudar o nome de "WIP" para "Solve"

2021-05-01 14:25 UTC, MatheusBlanco requested changes

2021-05-01 14:25 UTC, MatheusBlanco commented on src/pages/SubmitComplain/SubmitComplaitPhoto.tsx
> +
![image](https://user-images.githubusercontent.com/37380789/116785438-eb421380-aa6f-11eb-9213-a72acc026508.png)

O report do coverage fala que ainda faltam testar estas linhas

2021-05-01 14:32 UTC, MatheusBlanco requested changes

2021-05-01 14:32 UTC, MatheusBlanco commented on src/pages/SubmitComplain/SubmitComplaitPhoto.tsx
> +			alert('Arquivo muito grande, selecione outra imagem!');
Muda esse alerta para algo mais explicativo também. Ex: Tamanho da imagem não suportado

2021-05-08 14:02 UTC, MatheusBlanco approved these changes

2021-05-08 14:11 UTC, merged