WIP - #140 Geolocalização de denúncia
Eccoar/2020.2-eccoar_front-end pull request #23
Opened 2021-04-16 23:20 UTC by DLBrianPina

Neste pull request se realizou:
* Coletar geolocalização do usuário
* Escolha do ponto da denúncia

2021-04-17 16:15 UTC, MatheusBlanco commented
Como que tá esse PR? Posso corrigir ou ainda não?

2021-04-18 18:23 UTC, MatheusBlanco commented
@DLBrianPina @LuizPettengill

2021-04-19 17:05 UTC, MatheusBlanco requested changes
@DLBrianPina @LuizPettengill , testei o PR aqui na minha máquina mas não consegui cadastrar uma denúncia. O mapa está aparecendo picotado e não estou conseguindo clicar nele para avançar para a próxima página.

![image](https://user-images.githubusercontent.com/37380789/115275523-45f67980-a118-11eb-8619-d20706223267.png)

Os testes todos passaram mas deu um warning de unhandled exception:
![image](https://user-images.githubusercontent.com/37380789/115275570-573f8600-a118-11eb-8f84-54af59db832e.png)

2021-04-20 13:31 UTC, MatheusBlanco requested changes
Parabéns Brian! Só vou esperar, antes de aprovar pela adição do mapa na tela de detalhamento de denúncia, como conversamos no discord

2021-04-20 18:55 UTC, DLBrianPina commented
> Parabéns Brian! Só vou esperar, antes de aprovar pela adição do mapa na tela de detalhamento de denúncia, como conversamos no discord

Adicionei aqui 👍

2021-04-20 21:09 UTC, MatheusBlanco approved these changes

2021-04-22 15:20 UTC, Arthur-Matos requested changes
@DLBrianPina: Ótimo trabalho, a funcionalidade está adequada mas tenta concertar o hotspot que ta no Sonarcloud. O Saleh deu uma ideia ontem pro Blanco de como concertar. Fala com ele. Se não tiver como mesmo, o Sonarcloud ta indicando um Low priority então a gente pode avaliar de novo.
Concertando isso ta automaticamente aprovado

2021-04-23 20:37 UTC, Arthur-Matos approved these changes
Bom trabalho :+1: @DLBrianPina

2021-04-23 20:38 UTC, merged