WIP #139 Retirar upvote e voto de confirmação
Eccoar/2020.2-eccoar_front-end pull request #24
Opened 2021-04-17 03:04 UTC by luiz-herique

## Conteúdo

Neste pull request se realizou:
* Criação da logica para remover um voto;
* Testes relacionadas ao mesmo

## Checklist 
- [x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers). 
- [x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [x] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [x] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue). 
- [x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [x] Escrever o título do pull request no formato correto, conforme as referências abaixo:

2021-04-17 15:58 UTC, MatheusBlanco requested changes
Massa gente. Arrasaram. Mesma coisa dos outros PRs, queria saber como ficaria a questão dos testes, e estou vendo aqui funções de delete Complaint tbm

2021-04-17 15:58 UTC, MatheusBlanco commented on src/services/complaint.ts
> +			`/vote/remove?complaintId=${id}&userId=${userId}`,
lembrem de arrumar a rota aqui para /votes, para ficar igual ao gateway

2021-04-18 01:34 UTC, luiz-herique commented on src/services/complaint.ts
> +			`/vote/remove?complaintId=${id}&userId=${userId}`,
Alteração realizada, obrigado pelo feedback.

2021-04-18 13:50 UTC, MatheusBlanco commented on src/services/complaint.ts
> +			`/vote/remove?complaintId=${id}&userId=${userId}`,
Commitou aqui? Não chegou um commit novo. N esqueçam de ver os testes

2021-04-20 12:12 UTC, luiz-herique commented on src/services/complaint.ts
> +			`/vote/remove?complaintId=${id}&userId=${userId}`,
Alterei novamente para ficar no modelo REST

2021-04-21 22:54 UTC, Victor-Buendia commented
Tudo pronto nessa branch! @MatheusBlanco

2021-04-21 23:05 UTC, MatheusBlanco approved these changes
Parabéns galera!

2021-05-09 00:56 UTC, merged