WIP #153 Retirada de denúncia
Eccoar/2020.2-eccoar_front-end pull request #25
Opened 2021-04-17 03:18 UTC by luiz-herique

## Conteúdo

Neste pull request se realizou:

- Funcionalidade de deletar uma denuncia por aquele que a criou;

## Checklist

- [x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers).
- [x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [x] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [x] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue).
- [x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [x] Escrever o título do pull request no formato correto, conforme as referências abaixo:

2021-04-17 15:48 UTC, MatheusBlanco requested changes
Parabéns galera! Vejam essas alterações pequenas e queria saber se vão conseguir fazer os testes tbm.

2021-04-17 15:48 UTC, MatheusBlanco commented on src/pages/ComplaintDetails.tsx
> +								await deleteComplaint({
Tentem separar essa função daqui. Colocar ela separada junto das outras funções e só chamar ela aqui em baixo, com onClick={deleteComplaint}. Fica mais bonitinho

2021-04-17 15:48 UTC, MatheusBlanco commented on src/services/complaint.ts
> +			`/complaint/delete?id=${id}&userId=${userId}`,
Eu pedi no gateway para mexerem na rota, e aí lembrem de arrumar ela aqui tbm. Os parâmetros vão ser passados normalmente, mas o /complaint/delete vai virar /complaints apenas

2021-04-18 01:06 UTC, luiz-herique commented on src/services/complaint.ts
> +			`/complaint/delete?id=${id}&userId=${userId}`,
Obrigado pelo feedback, alteração realizada.

2021-04-18 13:52 UTC, MatheusBlanco commented on src/services/complaint.ts
> +			`/complaint/delete?id=${id}&userId=${userId}`,
Boa. Vejam de novo o comentário que eu deixei no PR do gateway, acho que vai ter mais alteração. E não se esqueçam dos testes, por favor

2021-04-20 12:13 UTC, luiz-herique commented on src/services/complaint.ts
> +			`/complaint/delete?id=${id}&userId=${userId}`,
Bom dia, vi o comentário, atualizei conforme orientado

2021-05-05 16:53 UTC, MatheusBlanco requested changes

2021-05-05 16:53 UTC, MatheusBlanco commented on src/tests/pages/ComplaitDetails.test.tsx
> +		userEvent.click(screen.getByText('Deletar Denúncia'));
Galera, está ótimo. Mas esse teste ainda está quebrando. Tiveram algum avanço?

Vejam os conflitos também

2021-05-08 22:13 UTC, MatheusBlanco approved these changes

2021-05-09 02:09 UTC, devsalula approved these changes

2021-05-09 02:09 UTC, devsalula commented on src/pages/Register/RegisterEmail.tsx
> +				console.log('skks');
console.log chapa

2021-05-09 02:09 UTC, devsalula commented on src/tests/pages/Register/RegisterEmail.test.tsx
>  		// FALTA INTEGRAR COM O BECK
Os cara já estão errados comentando no código. E no final ainda decidem comentar com Back escrito `BECK`. Só me resta saber se esse Beck é o nosso Back ou se é o Beck family friendly.

2021-05-09 02:56 UTC, Arthur-Matos reviewed
Resolve o conflito que eu aprovo

2021-05-09 13:51 UTC, merged