138 cadastro usuario
Eccoar/2020.2-eccoar_front-end pull request #27
Opened 2021-04-23 19:00 UTC by Sabanai104

## Conteúdo
Deve descrever de forma sucinta as principais alterações realizadas no pull request, de preferência em formato de bullet points.

Neste pull request se realizou:
* US 01
* Testes
* Criação das telas de cadastro seguindo o prototipo de alta fidelidade
* Integração com o back

2021-04-23 21:10 UTC, MatheusBlanco requested changes
Perfeito galera!. Queria só pedir para darem uma olhada nos comentários. Dois deles são coisas rápidas e o outro talvez seja mais chato, mas olhem aqui pfvr

2021-04-23 21:10 UTC, MatheusBlanco commented on src/components/Navbar.tsx
> +import arrow from '../assets/arrow.svg';
Esse import diz que não está sendo usado. Tira ele pfvr

2021-04-23 21:10 UTC, MatheusBlanco commented on src/components/Navbar.tsx
> +import { Link, useLocation } from 'react-router-dom';
Esse também

2021-04-23 21:10 UTC, MatheusBlanco commented on src/pages/Register/RegisterAdress.tsx
> +						/>
Vê se vc consegue colocar uma máscara de CPF aqui, e no CEP tbm. Dá uma olhada nessa lib [react-number-format](https://www.npmjs.com/package/react-number-format), acho q ela é bem de boas de se usar

2021-04-23 21:10 UTC, MatheusBlanco commented on src/tests/pages/SubmitComplain/SubmitComplainGeolocation.test.tsx
> +	...(jest.requireActual('react-router-dom') as typeof ReactRouterDom),
N sei se vc já viu, mas ele tá dando um erro nesse typeof ReactRouteDom

![image](https://user-images.githubusercontent.com/37380789/115929974-0f459980-a45f-11eb-9a2e-c03c12e830ff.png)
Diz que o jestMock não consegue acessar variáveis foram de escopo

2021-04-23 21:11 UTC, MatheusBlanco commented
E deu conflito tbm, aproveitem e deem rebase com a main

2021-04-25 14:57 UTC, luiz-herique commented on src/routes.tsx
> +				<Route component={Home} path='/home' />
Modificar a rota também nos lugares que a utilizam no código, como no arquivo Drawer.tsx:

							<Link
								className='side-drawer__text'
								to='/'
								onClick={close}
							>
								VER DENÚNCIAS
							</Link>

2021-04-26 15:41 UTC, MatheusBlanco requested changes
Perfeito. Mas queria apontar outras coisas que quebraram aqui nessa última alteração. Os testes que usam typeof ReactRouterDom ainda estão quebrados, alguns. Eles passam quando você mocka o reactRouterDom com jest.fn

```const mockReactRouterDom = jest.fn();```

e trocando typeof ReactRouterDom por typeof mockReactRouterDom, mas não sei até onde isso invalida o teste, então peço para que valide essa informação com o Féo.

O teste da setinha na navbar também quebrou, dá uma olhada nisso também e veja os warnings de imports e declarações não utilizadas.

2021-04-27 02:34 UTC, MatheusBlanco approved these changes
Boa Sabanai!

Antes de eu poder merjar, tira o useLocation que não tá sendo usado no routes.tsx, tira os console.logs tbm que vc deixou e arruma a pilha e commits por favor

2021-04-27 02:35 UTC, devsalula commented
@MatheusBlanco pelo amor de deus, não merja não. Ainda tem a pilha de commits para ajustar. Amanhã, eu vou ajudar o @Sabanai104 a corrigir isso.

2021-04-27 02:54 UTC, MatheusBlanco commented
> @MatheusBlanco pelo amor de deus, não merja não. Ainda tem a pilha de commits para ajustar. Amanhã, eu vou ajudar o @Sabanai104 a corrigir isso.

Não ia merjar não. Mas vou mudar pra request change pra n correr risco então

2021-04-27 02:55 UTC, MatheusBlanco requested changes
Esperando o conserto da pilha de commit

2021-04-27 20:15 UTC, luiz-herique approved these changes

2021-04-27 20:22 UTC, merged