Solve #167 Listar denúncias próximas do usuário
Eccoar/2020.2-eccoar_front-end pull request #28
Opened 2021-04-30 18:00 UTC by Victor-Buendia

## Conteúdo
Implementação de uma lógica nova para encaminhar os dados da geolocalização do usuário para a gateway

Neste pull request se realizou:
* US - Filtro de denúncia por localização
* Testes da implementação

## Checklist 
- [x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers). 
- [x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [x] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [x] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue). 
- [x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [x] Escrever o título do pull request no formato correto, conforme as referências abaixo: 

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:
* Solve #X IssueName (Caso Padrão)
* WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-05-01 14:52 UTC, MatheusBlanco requested changes
Amigo, perfeito. Queria pedir esse teste a mais e a alteração na rota https

2021-05-01 14:52 UTC, MatheusBlanco commented on src/pages/Home.tsx
> +				alert('Não foi possível obter sua localização!');
Faz um teste também para esse caso quando o usuário não consegue acessar a localização.

2021-05-01 14:52 UTC, MatheusBlanco commented on src/services/api.ts
> +const api = axios.create({ baseURL: `http://${url}/api` });
Volta esse pra https pra gente poder merjar e ele n quebrar em produção por favor.

2021-05-08 21:53 UTC, MatheusBlanco approved these changes

2021-05-09 02:32 UTC, Phe0 approved these changes

2021-05-09 02:32 UTC, merged