Solve #165 - Autenticação de usuário
Eccoar/2020.2-eccoar_front-end pull request #29
Opened 2021-05-01 14:58 UTC by DLBrianPina

Neste pull request se realizou:
* US 02
* Testes
* Context de autenticação do usuário

2021-05-01 15:38 UTC, MatheusBlanco requested changes
Perfeito. Vê as alterações que eu pedi e lembra de tirar os elementos da navbar da tela de login, menos a seta de return

2021-05-01 15:38 UTC, MatheusBlanco commented on src/components/Navbar.tsx
> +import React, { useEffect, useState } from 'react';
esse useEffect não está sendo usado. Tira por favor

2021-05-01 15:38 UTC, MatheusBlanco commented on src/routes.tsx
> +					<ProtectedRoute
No rebase tiveram 3 rotas iguais para a home, que estão zoando a proteção de rota. Arruma aqui pfvr

2021-05-01 15:39 UTC, MatheusBlanco requested changes

2021-05-01 15:39 UTC, MatheusBlanco commented on src/pages/Login.tsx
> +			<div className='login__buttonContainer'>
Arruma a cor desse botão, para a identidade visual e adiciona um link para a tela de cadastro também
![image](https://user-images.githubusercontent.com/37380789/116787415-3f51f580-aa7a-11eb-86f3-e6b30ffe6e26.png)

2021-05-01 15:57 UTC, MatheusBlanco requested changes

2021-05-01 15:57 UTC, MatheusBlanco commented on src/context/auth.tsx
> +					);
Esse alerta está com a mensagem errada. Estou colocando os dados errados e ele me avisa que o link foi enviado para o email
![image](https://user-images.githubusercontent.com/37380789/116787833-d0c26700-aa7c-11eb-9e34-81fdb01dcced.png)

2021-05-01 21:39 UTC, MatheusBlanco requested changes
@DLBrianPina , acho que o último commit quebrou dois testes, um da tela de registro e outro da tela de login.

![image](https://user-images.githubusercontent.com/37380789/116795580-717c4b00-aaac-11eb-8425-de4ce2b61636.png)

![image](https://user-images.githubusercontent.com/37380789/116795591-7b9e4980-aaac-11eb-8db0-305304c0c872.png)

2021-05-01 21:54 UTC, MatheusBlanco requested changes
Perfeito. Veja os testes, a questão da senha e tira os console.logs que ficaram do cadastro também por favor

2021-05-01 21:54 UTC, MatheusBlanco commented on src/pages/Login.tsx
> +						onChange={(e) => setPassword(e.target.value)}
Eu esqueci de comentar isso, perdão. Mas coloca algo pra ele esconder a senha por favor

2021-05-03 21:23 UTC, MatheusBlanco requested changes
Boa! Mais duas alteraçoes pequenas, a da api e um teste que passa mas dá um unhandledRejection no teste de complaint detail.

![image](https://user-images.githubusercontent.com/37380789/116935360-a1f2ef00-ac3c-11eb-9bfc-ed187535ffba.png)

2021-05-03 21:23 UTC, MatheusBlanco commented on src/services/api.ts
> +const protocol = process.env.NODE_ENV == 'production' ? 'https://' : 'http://';
esse protocol não está sendo usado. inclui ele na baseURL por favor

2021-05-03 21:25 UTC, MatheusBlanco requested changes

2021-05-03 21:25 UTC, MatheusBlanco commented on src/context/auth.tsx
> +export const useAuth = () => useContext(AuthContext);
Um erro está aparecendo quando eu abro a tela de detalhamento. O erro fala que o problema está nesta linha. O hook do useContext não está podendo ser usado fora de um componente react. Dá uma olhada por favor
![image](https://user-images.githubusercontent.com/37380789/116935573-e54d5d80-ac3c-11eb-8809-4d3550180242.png)

2021-05-04 17:43 UTC, MatheusBlanco approved these changes
Boa! Tem dois commits com a msm mensagem e um de merge. Faz o squash deles por favor

2021-05-04 17:48 UTC, MatheusBlanco requested changes
Vou deixar como request change só enquanto n arruma o squash de commit. Mas está aprovado

2021-05-04 17:48 UTC, devsalula requested changes
Olha a pilha de commit

2021-05-04 19:20 UTC, MatheusBlanco approved these changes

2021-05-07 02:49 UTC, luiz-herique approved these changes

2021-05-07 02:51 UTC, luiz-herique commented
Ficou ótimo, parabéns pelo trabalho

2021-05-07 03:44 UTC, devsalula requested changes
Algumas coisas aqui no Front:
1º Depois que o usuário se cadastra, ele está caindo diretamente na tela de login e só na tela de login, em que é solicitado para ele verificar o email. Por favor, modifiquem isso, mantenha a solicitação da verificação do próprio email na tela de login também, porém acrescentem essa mensagem logo na finalização do cadastro do usuário. 

2º O botão de "Cadastre-se" tá muito colado no botão de "Entrar", aumentem o espaçamento, por favor.
![photo_2021-05-06_23-38-44](https://user-images.githubusercontent.com/35435199/117390643-ed1f3300-aec4-11eb-8c75-f448fe703a8b.jpg)

2021-05-07 03:44 UTC, devsalula commented on src/tests/services/complaint.test.ts
> +			userId: 'aaa',
Coloca um mock melhor pfvr. Gera um uuid em qualquer site de mock e coloca aqui.

2021-05-07 03:44 UTC, devsalula commented on src/tests/services/complaint.test.ts
> +			userId: 'aaa',
Coloca um mock melhor pfvr. Gera um uuid em qualquer site de mock e coloca aqui.

2021-05-07 03:44 UTC, devsalula commented on package.json
> +		"@testing-library/react-hooks": "^5.1.2",
Para que?

2021-05-07 11:28 UTC, DLBrianPina commented on package.json
> +		"@testing-library/react-hooks": "^5.1.2",
O teste do hook "useAuth". Como hooks só podem ser chamados dentro do contexto de um provider, para os testes isso se torna impossível. Essa biblioteca simula o ambiente de um provider para que não ocorra um erro na chamada da função.

2021-05-15 19:02 UTC, devsalula approved these changes

2021-05-15 19:02 UTC, merged