Solve #71 Criação de componente estático - NavBar
Eccoar/2020.2-eccoar_front-end pull request #3
Opened 2021-03-10 19:19 UTC by DLBrianPina

Neste pull request se realizou:
* Criação do componente Navbar
* Adição do arquivo SVG do isotipo

2021-03-10 21:11 UTC, MatheusBlanco commented
Coloca a navbar pra aparecer na página inicial do boylerplate. Não vamos conseguir testar sem isso

2021-03-12 16:04 UTC, MatheusBlanco requested changes
Se puder alterar algumas coisas, a navbar é transparente, de acordo com o protótipo, e é um pouco menos alta tbm

2021-03-12 20:13 UTC, DLBrianPina commented
A altura foi alterada, porém o componente sempre esteve transparente

2021-03-12 21:06 UTC, MatheusBlanco approved these changes

2021-03-13 21:34 UTC, Phe0 approved these changes

2021-03-13 21:34 UTC, merged