Solve #70 Estudo de testes do front
Eccoar/2020.2-eccoar_front-end pull request #7
Opened 2021-03-13 20:39 UTC by Phe0

## Conteúdo
Foram adcionados testes para o componente Button, além de adicionar uma documentação sobre como testar os componentes no front.

Neste pull request se realizou:
* [Issue](https://github.com/fga-eps-mds/2020.2-Eccoar/issues/70)
* Teste no componente Button
* Documentação de como realizar testes

## Checklist 
- [x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers). 
- [x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [x] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue). 
- [x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [x] Escrever o título do pull request no formato correto, conforme as referências abaixo: 

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:
* Solve #X IssueName (Caso Padrão)
* WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-03-13 21:06 UTC, MatheusBlanco requested changes
Funciona mt bem. Só arrumar as mudanças que pedi no [PR](https://github.com/fga-eps-mds/2020.2-Eccoar/pull/96) da wiki

2021-03-13 21:22 UTC, Phe0 commented
arrumei @MatheusBlanco

2021-03-13 21:26 UTC, MatheusBlanco approved these changes

2021-03-13 21:26 UTC, MatheusBlanco commented
Aprovado

2021-03-14 02:56 UTC, devsalula approved these changes
Ótimo trabalho @Phe0!

2021-03-14 02:56 UTC, merged